project:
  type: website
  output-dir: docs

website:
  title: "Andrew-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-saul-uk
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

